services:
  airo-rebar-radar:
    build:
      context: .
    image: python3.14.2:trixie-slim-uv
    container_name: airo-rebar-radar
    tty: true
    ipc: host
    environment:
      - DISPLAY=${DISPLAY:-host.docker.internal:0}
      - QT_X11_NO_MITSHM=1
    volumes:
      - .:/root/airo-rebar-radar
      - /tmp/.X11-unix:/tmp/.X11-unix

  airo-rebar-radar-gpu:
    extends:
      service: airo-rebar-radar
    container_name: airo-rebar-radar-gpu
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    profiles:
      - gpu
